# left-side user profile
avatar: https://img-blog.csdnimg.cn/20210104144004284.jpg?x-oss-process=image/watermark,type_ZmFuZ3poZW5naGVpdGk,shadow_10,text_aHR0cHM6Ly9ibG9nLmNzZG4ubmV0L3dlaXhpbl80MjMyMTUxNw==,size_16,color_FFFFFF,t_70#pic_center# by default https://octodex.github.com/images/baracktocat.jpg
location: 佛山
email: 1529577833@qq.com
social:
  github: https://github.com/CoderWanFeng
  weibo: https://weibo.com/u/7411061007
  linkedin: http://www.python4office.cn/account-display/

# navbar menu
menu:
 archives: true
 tags: true
 categories: true

rss_dir: atom.xml

# widget
ga: # google analytics tracking code UA-XXXXXXX-X
baidutongji: # baidutongji tracking code
duoshuo: # duoshuo username
gcs: # google custom search code

# flagcounter
flagcounter_href: # https://info.flagcounter.com/xxxx
flagcounter_img_src: # https://s01.flagcounter.com/xxxx

# article_edit 在文章页显示跳转到编辑页
article_edit:
  enable: false #是否启用
  prefix: https://github.com/xxx/xxx/edit/master/source/  #编辑页前缀
