# Header

menu:
  ğŸè‡ªç”±èŒä¸š: /log/2026/freedom/0
  ğŸ¤å¾®ä¿¡: /wechat-qrcode/
  ğŸ“±è¿›ç¾¤: /wechat-group/
  ğŸ“•æ•™ç¨‹: https://www.python-office.com/
  ğŸ’´AI: https://mp.weixin.qq.com/s/M1jzQowv4Im2OYlvTJF7kg
#  å¼€æºé¡¹ç›®: /tags/å¼€æºé¡¹ç›®/

# SubNav
subnav:
  github: "https://github.com/CoderWanFeng/python-office"
  weibo: "https://weibo.com/u/7726957925"
  # rss: "#"
  zhihu: "https://www.zhihu.com/people/CoderWanFeng"
  qq: "https://mp.weixin.qq.com/s/yaSmFKO3RrBpyanW3nvRAQ"
  weixin: "http://www.python4office.cn/wechat-qrcode/"
  #jianshu: "#"
  #douban: "#"
  #segmentfault: "#"
  bilibili: "https://space.bilibili.com/259649365"
  acfun: "https://www.acfun.cn/u/35901274"
  mail: "https://cos.python-office.com/wechat/qr-code.jpg"
  google: "https://www.youtube.com/channel/UCtg1O5pVbuch1sVk_ELr7Hg/"
  facebook: "https://www.facebook.com/matthew.liu.3551"
  twitter: "https://x.com/CoderWanFeng"
  # linkedin: "https://www.bilibili.com/video/BV1Nr4y1B76X"

rss: /atom.xml

# æ˜¯å¦éœ€è¦ä¿®æ”¹ root è·¯å¾„
# å¦‚æœæ‚¨çš„ç½‘ç«™å­˜æ”¾åœ¨å­ç›®å½•ä¸­ï¼Œä¾‹å¦‚ http://yoursite.com/blogï¼Œ
# è¯·å°†æ‚¨çš„ url è®¾ä¸º http://yoursite.com/blog å¹¶æŠŠ root è®¾ä¸º /blog/ã€‚
root: /

# visitors count
counter: true

# Content

# æ–‡ç« å¤ªé•¿ï¼Œæˆªæ–­æŒ‰é’®æ–‡å­—
excerpt_link: more
# æ–‡ç« å¡ç‰‡å³ä¸‹è§’å¸¸é©»é“¾æ¥ï¼Œä¸éœ€è¦è¯·è®¾ç½®ä¸ºfalse
show_all_link: 'å±•å¼€å…¨æ–‡'
# æ•°å­¦å…¬å¼
mathjax: false
# æ˜¯å¦åœ¨æ–°çª—å£æ‰“å¼€é“¾æ¥
open_in_new: true

# æ‰“èµ
# æ‰“èµtypeè®¾å®šï¼š0-å…³é—­æ‰“èµï¼› 1-æ–‡ç« å¯¹åº”çš„mdæ–‡ä»¶é‡Œæœ‰reward:trueå±æ€§ï¼Œæ‰æœ‰æ‰“èµï¼› 2-æ‰€æœ‰æ–‡ç« å‡æœ‰æ‰“èµ
reward_type: 2
# æ‰“èµwording
reward_wording: 'å—¨ï¼Œæ‰«ç  è¿›ç¾¤'
# æ”¯ä»˜å®äºŒç»´ç å›¾ç‰‡åœ°å€ï¼Œè·Ÿä½ è®¾ç½®å¤´åƒçš„æ–¹å¼ä¸€æ ·ã€‚æ¯”å¦‚ï¼š/assets/img/alipay.jpg
alipay:
# å¾®ä¿¡äºŒç»´ç å›¾ç‰‡åœ°å€
weixin: https://website-python-1300615378.cos.ap-nanjing.myqcloud.com/%E5%BC%95%E5%AF%BC%E8%B6%85%E9%93%BE%E6%8E%A5/4n-group.png
# ç›®å½•
# ç›®å½•è®¾å®šï¼š0-ä¸æ˜¾ç¤ºç›®å½•ï¼› 1-æ–‡ç« å¯¹åº”çš„mdæ–‡ä»¶é‡Œæœ‰toc:trueå±æ€§ï¼Œæ‰æœ‰ç›®å½•ï¼› 2-æ‰€æœ‰æ–‡ç« å‡æ˜¾ç¤ºç›®å½•
toc: 2
# æ ¹æ®è‡ªå·±çš„ä¹ æƒ¯æ¥è®¾ç½®ï¼Œå¦‚æœä½ çš„ç›®å½•æ ‡é¢˜ä¹ æƒ¯æœ‰æ ‡å·ï¼Œç½®ä¸ºtrueå³å¯éšè—hexoé‡å¤çš„åºå·ï¼›å¦åˆ™ç½®ä¸ºfalse
toc_hide_index: true
# ç›®å½•ä¸ºç©ºæ—¶çš„æç¤º
toc_empty_wording: 'ç›®å½•ï¼Œä¸å­˜åœ¨çš„â€¦'

# æ˜¯å¦æœ‰å¿«é€Ÿå›åˆ°é¡¶éƒ¨çš„æŒ‰é’®
top: true

# Miscellaneous
baidu_analytics: 'a8a4322ff49ea1111171ed84ea70baa6'
google_analytics: ''
favicon: https://raw.atomgit.com/CoderWanFeng1/website/raw/main/icon4.jpg

#ä½ çš„å¤´åƒurl
avatar: https://raw.atomgit.com/CoderWanFeng1/website/raw/main/icon4.jpg

#æ˜¯å¦å¼€å¯åˆ†äº«
share_jia: true

#è¯„è®ºï¼š1ã€å¤šè¯´ï¼›2ã€ç½‘æ˜“äº‘è·Ÿå¸–ï¼›3ã€ç•…è¨€ï¼›4ã€Disqusï¼›5ã€Gitment
#ä¸éœ€è¦ä½¿ç”¨æŸé¡¹ï¼Œç›´æ¥è®¾ç½®å€¼ä¸ºfalseï¼Œæˆ–æ³¨é‡Šæ‰
#å…·ä½“è¯·å‚è€ƒwikiï¼šhttps://github.com/litten/hexo-theme-yilia/wiki/

#1ã€å¤šè¯´
duoshuo: false

#2ã€ç½‘æ˜“äº‘è·Ÿå¸–
wangyiyun: false

#3ã€ç•…è¨€
#changyan_appid: 'cyvOjMKDi'
#changyan_conf: 'e7a3f9de2303b2e519315ab135318536'

#4ã€Disqus åœ¨hexoæ ¹ç›®å½•çš„configé‡Œä¹Ÿæœ‰disqus_shortnameå­—æ®µï¼Œä¼˜å…ˆä½¿ç”¨yiliaçš„
disqus: false

#5ã€Gitment
gitment_owner: false      #ä½ çš„ GitHub ID
gitment_repo: ''          #å­˜å‚¨è¯„è®ºçš„ repo
gitment_oauth:
  client_id: ''           #client ID
  client_secret: ''       #client secret

# æ ·å¼å®šåˆ¶ - ä¸€èˆ¬ä¸éœ€è¦ä¿®æ”¹ï¼Œé™¤éæœ‰å¾ˆå¼ºçš„å®šåˆ¶æ¬²æœ›â€¦
style:
  # å¤´åƒä¸Šé¢çš„èƒŒæ™¯é¢œè‰²
  header: '#4d4d4d'
  # å³æ»‘æ¿å—èƒŒæ™¯
  slider: 'linear-gradient(200deg,#a0cfe4,#e8c37e)'

# sliderçš„è®¾ç½®
slider:
  # æ˜¯å¦é»˜è®¤å±•å¼€tagsæ¿å—
  showTags: true

# æ™ºèƒ½èœå•
# å¦‚ä¸éœ€è¦ï¼Œå°†è¯¥å¯¹åº”é¡¹ç½®ä¸ºfalse
# æ¯”å¦‚
#smart_menu:
#  friends: false
smart_menu:
  innerArchive: 'æ‰€æœ‰æ–‡ç« '
  friends: 'å‹é“¾'
  aboutme: 'å…³äºæ™šæ«'

# friends:
#   äº¤æµç¾¤: http://python4office.cn/wechat-group/
#   èµ„æºåˆé›†: https://blog.csdn.net/weixin_42321517
#   äº‘æœåŠ¡å™¨: https://www.aliyun.com/minisite/goods?userCode=t6duaoe1
#   æ•°æ®åˆ†æ: http://gk.link/a/1193m
#   è‡ªåŠ¨åŒ–åŠå…¬: https://www.python-office.com/video/video.html

aboutme: ç¼–ç¨‹åšä¸»ï¼Œå…¨ç½‘ç²‰ä¸30w+ï¼Œå¼€æºé¡¹ç›®ï¼špython-officeï¼Œæˆ‘çš„å¾®ä¿¡ï¼šwfdev7
